### ISSUE TITLE
The tutorial's web page doesn't work anymore

### ISSUE THREAD

**Issue by patrykchodur** [W-J-Dev-School/CHIP-8-Emulator#1]
The web page from the top of the README.md file (https://wjdevschool.com/blog/video-game-console-emulator/) now links to some malicious server. Is the tutorial available somewhere with a new link?

**Comment by wbogocki** [comment]
I stopped using the website and let the domain expire. I guess someone took it over. Will update the link tomorrow.

There's a copy on medium/you can probably find it on the internet archive:
https://wbogocki.medium.com/how-to-code-a-game-console-emulator-7a75959d865

**Comment by patrykchodur** [comment]
Great, thanks!
